// react-app/src/components/Product.js
import React from 'react';

const Product = ({ id, name, isSoldOut, onBuyClick }) => {
  const handleClick = () => {
    onBuyClick(id)
  }

  return (
    <div>
      <span style={ { textDecoration: isSoldOut ? 'line-through' : 'none' }}>
        { name }
      </span>
      <button onClick={ handleClick }>
        Buy
      </button>
    </div>
  )
};

export default Product;

// vue-app/src/components/Product.vue
<template>
  <div>
    <span v-bind:style="{ textDecoration: isSoldOut ? 'line-through' : 'none' }">
    {{ name }}
    </span>
    <button v-on:click="handleClick">
      Buy
    </button>
  </div>
</template>

<script>
export default {
  name: 'product',
  props: ['id', 'name', 'isSoldOut'],
  methods: {
    handleClick () {
      this.$emit('buy-click', this.id)
    }
  }
}
</script>

<style scoped>
</style>
