// vue-app/src/components/AddProduct.vue
<template>
  <form v-on:submit.prevent="handleSubmit(product)">
    <input v-model="product.name">
    <button>Submit</button>
  </form>
</template>

<script>
import { mapActions } from 'vuex'

export default {
  name: 'add-product',
  data () {
    return {
      product: {
        name: ''
      }
    }
  },
  methods: {
    ...mapActions(['addProduct']),
    handleSubmit (product) {
      this.addProduct(product)
      this.$router.push('/products')
    }
  }
}
</script>

<style scoped>
</style>

// react-app/src/containers/AddProduct.js
import React from 'react';
import { connect } from 'react-redux';
import { LocalForm, Control } from 'react-redux-form';
import { withRouter } from 'react-router-dom';

const AddProductComponent = ({ onAddProductClick, history }) => {
  const handleAddProductSubmit = product => {
    onAddProductClick(product);
    history.push('/products');
  };

  return (
    <LocalForm onSubmit={ handleAddProductSubmit }
    >
      <Control.text model=".name" />
      <button>Submit</button>
    </LocalForm>
  );
}

const mapStateToProps = state => ({
  products: state
});

const mapDispatchToProps = dispatch => ({
  onAddProductClick(product) {
    dispatch({type: 'ADD_PRODUCT', payload: { product } })
  }
});


export default withRouter(connect(mapStateToProps, mapDispatchToProps)(AddProductComponent));
