// react-app/src/components/Product.js
import React from 'react';

const Product = ({ id, name, isSoldOut, onBuyClick }) => {
  const handleClick = () => {
    onBuyClick(id)
  }

  return (
    <div>
      <span style={ { textDecoration: isSoldOut ? 'line-through' : 'none' }}>
        { name }
      </span>
      <button onClick={ handleClick }>
        Buy
      </button>
    </div>
  )
};

export default Product;

// angular-app/src/app/shared/product/product.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.css']
})
export class ProductComponent implements OnInit {
  @Input() id: number;
  @Input() name: string;
  @Input() isSoldOut: boolean;
  @Output() onBuyClick = new EventEmitter();

  constructor() { }

  ngOnInit() {
  }

  handleBuyClick() {
    this.onBuyClick.emit(this.id);
  }
}

<div>
  <span [style.textDecoration]="isSoldOut ? 'line-through' : 'none'">
    {{ name }}
  </span>
  <button (click)="handleBuyClick(id)">
    Buy
  </button>
</div>
